version: '3'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: Dockerfile-frontenvoy
    image: yiyouguisu/envoy-circuit_breaker:latest
    privileged: true
    networks:
      - circuit_breaker_network
    expose:
      - "80"
      - "9901"
    ports:
      - "80:80"
      - "9901:9901"

  # service1: &service1
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile-service1
  #   networks:
  #     circuit_breaker_network:
  #   environment:
  #     - SERVICE_NAME=1
  #   expose:
  #     - "80"

  # service1-1:
  #   <<: *service1

  # service1-2:
  #   <<: *service1

  # service1-3:
  #   <<: *service1

  service2:
    build:
      context: ./
      dockerfile: Dockerfile-service2
    networks:
      circuit_breaker_network:
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
    
networks:
  circuit_breaker_network: {}
