FROM frolvlad/alpine-glibc

RUN apk upgrade && apk add curl && apk add iptables

ADD ./envoy /
RUN chmod u+x /envoy

ADD ./front-envoy.yaml /etc/


CMD /envoy --v2-config-only -l debug -c /etc/front-envoy.yaml --service-node front-node --service-cluster front-cluster
